FROM python:3.6.6-slim-stretch # Use a slim Python 3.6.6 base image based on Debian Stretch

COPY requirements.txt . # Copy the requirements file to the image
RUN pip install --upgrade -r requirements.txt # Install Python dependencies

COPY api api # Copy the application code to the image

ENTRYPOINT [ "python3.6", "/api/flask_elector.py" ] # Define the entrypoint to run the Flask elector application

# Comment: Build the image with: sudo docker build -t elector -f Dockerfile_elector .
# Comment: Run the container with: sudo docker run -p 5002:5002 elector
